uploads = []
outputs = []

[[generated]]
id = "51txJcgHXkwghLjdnupH9"
uri = "file://artifacts/dotfit/public/hero.png"
type = "image"
title = "Cinematic gym hero image"

[[generated]]
id = "Q20AQbFYhcaJ0K7IPhjg1"
uri = "file://artifacts/dotfit/public/class-zumba.png"
type = "image"
title = "Zumba class group"

[[generated]]
id = "krQJdRI_OwdOraqPe7eE8"
uri = "file://artifacts/dotfit/public/class-kickboxing.png"
type = "image"
title = "Kickboxing training"

[[generated]]
id = "4vV-azsq4udM2g8dJzgSC"
uri = "file://artifacts/dotfit/public/class-yoga.png"
type = "image"
title = "Yoga and Pilates"

[[generated]]
id = "xOQYqpGnhtSaQGscYu1b_"
uri = "file://artifacts/dotfit/public/facility-equipment.png"
type = "image"
title = "Gym equipment area"

[[generated]]
id = "EfxMP0K4Yty1IANSnDlL-"
uri = "file://artifacts/dotfit/public/facility-sauna.png"
type = "image"
title = "Sauna and Steam room"

[[generated]]
id = "Dw6EqET4Ii_yfYEAXCkS3"
uri = "file://artifacts/dotfit/public/trainer-1.png"
type = "image"
title = "Expert personal trainer"

[[generated]]
id = "5zd6UGz2P94VVe69390B9"
uri = "file://artifacts/dotfit/public/trainer-2.png"
type = "image"
title = "Expert female trainer"

[[generated]]
id = "1nMgGmccQWlqY-_U7VHhv"
uri = "file://artifacts/dotfit/public/trainer-ganesh.png"
type = "image"
title = "Male Indian gym trainer 1"

[[generated]]
id = "SYEcmd7X_A16-0hkVaHat"
uri = "file://artifacts/dotfit/public/trainer-rupali.png"
type = "image"
title = "Female Indian gym trainer"

[[generated]]
id = "XFJPkf3_cI0hJLTFrWhtD"
uri = "file://artifacts/dotfit/public/trainer-poonam.png"
type = "image"
title = "Male Indian yoga trainer"

[[generated]]
id = "4vlmCBE0zMfXIsf6x-lxw"
uri = "file://artifacts/dotfit/public/trainer-sikandar.png"
type = "image"
title = "Male Indian zumba trainer"

[[generated]]
id = "J756H43_UQMJ_Qn2s_-fm"
uri = "file://artifacts/dotfit/public/transformation-1.png"
type = "image"
title = "Gym transformation before after"
